/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

import java.awt.BorderLayout;
import ui.dialog.LamBai;

/**
 *
 * @author Admin
 */
import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;
import ui.MainFrame;

public class BaiKiemTra extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private dao.ChuDeDAO chuDeDAO = new dao.ChuDeDAO();
    private dao.KetQuaKiemTraDAO ketQuaKiemTraDAO = new dao.KetQuaKiemTraDAO();

    /**
     * Creates new form BaiKiemTra
     */
    public BaiKiemTra() {
        initComponents();
    }

    public BaiKiemTra(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        loadChuDeComboBox();
        loadData();
    }

    private models.TaiKhoan getCurrentUser() {
        if (mainFrame != null) {
            return mainFrame.getCurrentUser();
        }
        java.awt.Container parent = SwingUtilities.getWindowAncestor(this);
        if (parent instanceof MainFrame) {
            return ((MainFrame) parent).getCurrentUser();
        }
        return null;
    }

    public void loadChuDeComboBox() {
        comboboxChuDe.removeAllItems();
        for (models.ChuDe cd : chuDeDAO.selectAll()) {
            comboboxChuDe.addItem(cd.getTenChuDe());
        }
    }

    public void loadData() {
        models.TaiKhoan user = getCurrentUser();
        if (user == null || comboboxChuDe.getSelectedItem() == null) {
            return;
        }
        
        String tenCD = comboboxChuDe.getSelectedItem().toString();
        models.ChuDe cd = chuDeDAO.selectByName(tenCD);
        if (cd == null) return;
        
        double maxScore = ketQuaKiemTraDAO.getMaxDiemChuDe(user.getMaTaiKhoan(), cd.getMaChuDe());
        int attemptCount = ketQuaKiemTraDAO.getSoLanLamChuDe(user.getMaTaiKhoan(), cd.getMaChuDe());
        double avgScore = ketQuaKiemTraDAO.getDiemTrungBinhChuDe(user.getMaTaiKhoan(), cd.getMaChuDe());
        
        lbldiemMaxChuDe.setText(String.format("%.2f", maxScore));
        lblSoLanLam.setText(String.valueOf(attemptCount));
        lblDiemTrungBinhChuDe.setText(String.format("%.2f", avgScore));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboboxChuDe = new javax.swing.JComboBox<>();
        lblLamBaiKiemTra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbldiemMaxChuDe = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSoLanLam = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDiemTrungBinhChuDe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Chọn chủ đề:");

        comboboxChuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxChuDeActionPerformed(evt);
            }
        });

        lblLamBaiKiemTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check-solid.png"))); // NOI18N
        lblLamBaiKiemTra.setText("Làm bài kiểm tra");
        lblLamBaiKiemTra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 118, 110), 3, true));
        lblLamBaiKiemTra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLamBaiKiemTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLamBaiKiemTraMousePressed(evt);
            }
        });

        jLabel2.setText("Điểm cao nhất");

        lbldiemMaxChuDe.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lbldiemMaxChuDe.setForeground(new java.awt.Color(15, 118, 110));
        lbldiemMaxChuDe.setText("9.25");

        jLabel3.setText("Số lần làm");

        lblSoLanLam.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblSoLanLam.setForeground(new java.awt.Color(15, 118, 110));
        lblSoLanLam.setText("1");

        jLabel4.setText("Điểm trung bình của chủ đề");

        lblDiemTrungBinhChuDe.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblDiemTrungBinhChuDe.setForeground(new java.awt.Color(15, 118, 110));
        lblDiemTrungBinhChuDe.setText("8.625");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboboxChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLamBaiKiemTra, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbldiemMaxChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblSoLanLam, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblDiemTrungBinhChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboboxChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblDiemTrungBinhChuDe))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblSoLanLam))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbldiemMaxChuDe)))
                .addGap(18, 18, 18)
                .addComponent(lblLamBaiKiemTra)
                .addContainerGap(571, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblLamBaiKiemTraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLamBaiKiemTraMousePressed
        if (comboboxChuDe.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một chủ đề để làm bài!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        models.TaiKhoan user = getCurrentUser();
        if (user == null) {
            return;
        }
        
        String tenCD = comboboxChuDe.getSelectedItem().toString();
        models.ChuDe cd = chuDeDAO.selectByName(tenCD);
        if (cd == null) return;
        
        LamBai dialog = new LamBai(null, true);
        GiaoDienLamBai panel = new GiaoDienLamBai();
        panel.setupTest(user.getMaTaiKhoan(), cd.getMaChuDe());
        
        dialog.getContentPane().removeAll();
        dialog.getContentPane().setLayout(new BorderLayout());
        dialog.getContentPane().add(panel, BorderLayout.CENTER);

        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        
        // Refresh statistics after user completes the test
        loadData();
    }//GEN-LAST:event_lblLamBaiKiemTraMousePressed

    private void comboboxChuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxChuDeActionPerformed
        loadData();
    }//GEN-LAST:event_comboboxChuDeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxChuDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDiemTrungBinhChuDe;
    private javax.swing.JLabel lblLamBaiKiemTra;
    private javax.swing.JLabel lblSoLanLam;
    private javax.swing.JLabel lbldiemMaxChuDe;
    // End of variables declaration//GEN-END:variables
}
