/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

import java.awt.BorderLayout;
import ui.dialog.LamBai;

/**
 *
 * @author Admin
 */
public class BaiKiemTra extends javax.swing.JPanel {

    /**
     * Creates new form BaiKiemTra
     */
    public BaiKiemTra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboboxChuDe = new javax.swing.JComboBox<>();
        lblLamBaiKiemTra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbldiemMaxChuDe = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSoLanLam = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDiemTrungBinhChuDe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Chọn chủ đề:");

        comboboxChuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxChuDeActionPerformed(evt);
            }
        });

        lblLamBaiKiemTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check-solid.png"))); // NOI18N
        lblLamBaiKiemTra.setText("Làm bài kiểm tra");
        lblLamBaiKiemTra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        lblLamBaiKiemTra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLamBaiKiemTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLamBaiKiemTraMousePressed(evt);
            }
        });

        jLabel2.setText("Điểm cao nhất");

        lbldiemMaxChuDe.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lbldiemMaxChuDe.setForeground(new java.awt.Color(0, 204, 102));
        lbldiemMaxChuDe.setText("9.25");

        jLabel3.setText("Số lần làm");

        lblSoLanLam.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblSoLanLam.setForeground(new java.awt.Color(0, 204, 102));
        lblSoLanLam.setText("1");

        jLabel4.setText("Điểm trung bình của chủ đề");

        lblDiemTrungBinhChuDe.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblDiemTrungBinhChuDe.setForeground(new java.awt.Color(0, 204, 102));
        lblDiemTrungBinhChuDe.setText("8.625");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboboxChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLamBaiKiemTra, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbldiemMaxChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblSoLanLam, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblDiemTrungBinhChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboboxChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblDiemTrungBinhChuDe))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblSoLanLam))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbldiemMaxChuDe)))
                .addGap(18, 18, 18)
                .addComponent(lblLamBaiKiemTra)
                .addContainerGap(571, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblLamBaiKiemTraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLamBaiKiemTraMousePressed
        // TODO add your handling code here:
        LamBai dialog = new LamBai(null, true);
        GiaoDienLamBai panel = new GiaoDienLamBai();
        dialog.getContentPane().removeAll();
        dialog.getContentPane().setLayout(new BorderLayout());
        dialog.getContentPane().add(panel, BorderLayout.CENTER);

        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_lblLamBaiKiemTraMousePressed

    private void comboboxChuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxChuDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxChuDeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxChuDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDiemTrungBinhChuDe;
    private javax.swing.JLabel lblLamBaiKiemTra;
    private javax.swing.JLabel lblSoLanLam;
    private javax.swing.JLabel lbldiemMaxChuDe;
    // End of variables declaration//GEN-END:variables
}
