/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class CapNhatChuDe extends javax.swing.JPanel {

    /**
     * Creates new form ThemChuDe
     */
    public CapNhatChuDe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtChuDe = new javax.swing.JTextField();
        lblChuDe = new javax.swing.JLabel();
        lblThemChuDe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 204, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬT CHỦ ĐỀ");
        jLabel1.setOpaque(true);

        jLabel2.setText("Tên chủ đề");

        lblChuDe.setBackground(new java.awt.Color(0, 205, 102));
        lblChuDe.setForeground(new java.awt.Color(255, 255, 255));
        lblChuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuDe.setText("Cập nhật");
        lblChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblChuDe.setOpaque(true);
        lblChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblChuDeMousePressed(evt);
            }
        });

        lblThemChuDe.setBackground(new java.awt.Color(255, 0, 0));
        lblThemChuDe.setForeground(new java.awt.Color(255, 255, 255));
        lblThemChuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThemChuDe.setText("Hủy");
        lblThemChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThemChuDe.setOpaque(true);
        lblThemChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblThemChuDeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblThemChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThemChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblThemChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemChuDeMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_lblThemChuDeMousePressed
    public void setTenChuDe(String tenChuDe){
        txtChuDe.setText(tenChuDe);
    }
    
    private void lblChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChuDeMousePressed
        // TODO add your handling code here:
        String chude = txtChuDe.getText();
        System.out.println(chude.length());
        if ("".equals(chude)) {
            JOptionPane.showMessageDialog(null, "Chủ đề không được để trống!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            
        } else {
            // thêm vào csdl (gọi từ service)
            JOptionPane.showMessageDialog(null, "Thêm thành công!", "Thông tin", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_lblChuDeMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblChuDe;
    private javax.swing.JLabel lblThemChuDe;
    private javax.swing.JTextField txtChuDe;
    // End of variables declaration//GEN-END:variables
}
