/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Admin
 */
public class CapNhatChuDe extends javax.swing.JPanel {

    /**
     * Creates new form ThemChuDe
     */
    public CapNhatChuDe() {
        initComponents();
        txtMaChuDe.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenChuDe = new javax.swing.JTextField();
        lblCapNhatChuDe = new javax.swing.JLabel();
        lblHuyCapNhatChuDe = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaChuDe = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(248, 250, 252));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬT CHỦ ĐỀ");
        jLabel1.setOpaque(true);

        jLabel2.setText("Tên chủ đề");

        lblCapNhatChuDe.setBackground(new java.awt.Color(15, 118, 110));
        lblCapNhatChuDe.setForeground(new java.awt.Color(255, 255, 255));
        lblCapNhatChuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCapNhatChuDe.setText("Cập nhật");
        lblCapNhatChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCapNhatChuDe.setOpaque(true);
        lblCapNhatChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCapNhatChuDeMousePressed(evt);
            }
        });

        lblHuyCapNhatChuDe.setBackground(new java.awt.Color(255, 0, 0));
        lblHuyCapNhatChuDe.setForeground(new java.awt.Color(255, 255, 255));
        lblHuyCapNhatChuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuyCapNhatChuDe.setText("Hủy");
        lblHuyCapNhatChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHuyCapNhatChuDe.setOpaque(true);
        lblHuyCapNhatChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHuyCapNhatChuDeMousePressed(evt);
            }
        });

        jLabel3.setText("Mã chủ đề");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblCapNhatChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblHuyCapNhatChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMaChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapNhatChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHuyCapNhatChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblHuyCapNhatChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuyCapNhatChuDeMousePressed
        // TODO add your handling code here:
        JDialog frame = (JDialog) SwingUtilities.getWindowAncestor(this);
            frame.dispose();
    }//GEN-LAST:event_lblHuyCapNhatChuDeMousePressed
    public void setTenChuDe(String tenChuDe){
        txtTenChuDe.setText(tenChuDe);
    }
    
    public void setMaChuDe(String maChuDe){
        txtMaChuDe.setText(maChuDe);
    }
    
    private void lblCapNhatChuDeMousePressed(java.awt.event.MouseEvent evt) {
        String maCD = txtMaChuDe.getText().trim();
        String chude = txtTenChuDe.getText().trim();
        if (maCD.isEmpty() || chude.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mã chủ đề và tên chủ đề không được để trống!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = Integer.parseInt(maCD);
        dao.ChuDeDAO chuDeDAO = new dao.ChuDeDAO();
        models.ChuDe existing = chuDeDAO.selectByName(chude);
        
        if (existing != null && existing.getMaChuDe() != id) {
            JOptionPane.showMessageDialog(null, "Tên chủ đề đã tồn tại trên một chủ đề khác!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        models.ChuDe cd = new models.ChuDe(id, chude);
        if (chuDeDAO.update(cd)) {
            JOptionPane.showMessageDialog(null, "Cập nhật chủ đề thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            JDialog frame = (JDialog) SwingUtilities.getWindowAncestor(this);
            frame.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Cập nhật chủ đề thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCapNhatChuDe;
    private javax.swing.JLabel lblHuyCapNhatChuDe;
    private javax.swing.JTextField txtMaChuDe;
    private javax.swing.JTextField txtTenChuDe;
    // End of variables declaration//GEN-END:variables
}
