/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import ui.frame.LoginFrame;

/**
 *
 * @author Admin
 */
public class GiaoDienLamBai extends javax.swing.JPanel {

    /**
     * Creates new form GiaoDienLamBai
     */
    public GiaoDienLamBai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DapAn = new javax.swing.ButtonGroup();
        lblNopBai = new javax.swing.JLabel();
        lblThoat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblChuDe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSoCauDaHoanThanh = new javax.swing.JLabel();
        lblCauHoi = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        lblPrev = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblSoThuTuCau = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblNopBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle-xmark-solid.png"))); // NOI18N
        lblNopBai.setText("Thoát");
        lblNopBai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        lblNopBai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNopBai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNopBaiMousePressed(evt);
            }
        });

        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check-solid.png"))); // NOI18N
        lblThoat.setText("Nộp bài");
        lblThoat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        lblThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblThoatMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LÀM BÀI KIỂM TRA CỦA CHỦ ĐỀ");
        jLabel1.setOpaque(true);

        jLabel2.setText("Chủ đề: ");

        lblChuDe.setForeground(new java.awt.Color(255, 0, 0));
        lblChuDe.setText("Tên chủ đề");

        jLabel4.setText("Số câu đã hoàn thành");

        lblSoCauDaHoanThanh.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblSoCauDaHoanThanh.setForeground(new java.awt.Color(0, 204, 102));
        lblSoCauDaHoanThanh.setText("1");

        lblCauHoi.setText("Câu hỏi");

        DapAn.add(radio1);
        radio1.setText("A / T");
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });

        DapAn.add(radio2);
        radio2.setText("B / F");

        DapAn.add(radio3);
        radio3.setText("C");

        DapAn.add(radio4);
        radio4.setText("D");

        lblPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/chevron-left-solid.png"))); // NOI18N
        lblPrev.setText("Câu trước");
        lblPrev.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        lblPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPrevMousePressed(evt);
            }
        });

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/angle-right-solid.png"))); // NOI18N
        lblNext.setText("Câu kế tiếp");
        lblNext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNextMousePressed(evt);
            }
        });

        lblSoThuTuCau.setFont(new java.awt.Font("UTM HelvetIns", 0, 14)); // NOI18N
        lblSoThuTuCau.setForeground(new java.awt.Color(0, 204, 102));
        lblSoThuTuCau.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblChuDe))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(lblSoCauDaHoanThanh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radio1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                        .addComponent(radio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNext, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNopBai, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSoThuTuCau, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblChuDe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblSoCauDaHoanThanh))
                .addGap(36, 36, 36)
                .addComponent(lblSoThuTuCau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCauHoi)
                .addGap(18, 18, 18)
                .addComponent(radio1)
                .addGap(18, 18, 18)
                .addComponent(radio2)
                .addGap(18, 18, 18)
                .addComponent(radio3)
                .addGap(18, 18, 18)
                .addComponent(radio4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNopBai)
                        .addComponent(lblThoat))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPrev)
                        .addComponent(lblNext)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblNopBaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNopBaiMousePressed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(
                this,
                "Bạn có muốn thoát làm bài? Lần làm bài này sẽ không được ghi nhận vào hệ thống.",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION
        );

        if (chon == JOptionPane.YES_OPTION) {
            JDialog frame = (JDialog) SwingUtilities.getWindowAncestor(this);
            frame.dispose();
        }
    }//GEN-LAST:event_lblNopBaiMousePressed

    private void lblThoatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThoatMousePressed

    private void lblPrevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrevMousePressed

    }//GEN-LAST:event_lblPrevMousePressed

    private void lblNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNextMousePressed

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup DapAn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCauHoi;
    private javax.swing.JLabel lblChuDe;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblNopBai;
    private javax.swing.JLabel lblPrev;
    private javax.swing.JLabel lblSoCauDaHoanThanh;
    private javax.swing.JLabel lblSoThuTuCau;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    // End of variables declaration//GEN-END:variables
}
