/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

/**
 *
 * @author Admin
 */
public class HocTu extends javax.swing.JPanel {

    /**
     * Creates new form HocTu
     */
    public HocTu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboboxChuDe = new javax.swing.JComboBox<>();
        lblTuHienTaiTrenSoTu = new javax.swing.JLabel();
        lblEng = new javax.swing.JLabel();
        lblPrev = new javax.swing.JLabel();
        lblFlip = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblVie = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Chọn chủ đề:");

        lblTuHienTaiTrenSoTu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTuHienTaiTrenSoTu.setText("Từ hiện tại/Số từ");

        lblEng.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblEng.setForeground(new java.awt.Color(255, 0, 0));
        lblEng.setText("English word");

        lblPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/chevron-left-solid.png"))); // NOI18N
        lblPrev.setText("Từ trước");
        lblPrev.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        lblPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPrevMousePressed(evt);
            }
        });

        lblFlip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrows-rotate-solid.png"))); // NOI18N
        lblFlip.setText("Lật");
        lblFlip.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        lblFlip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFlip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFlipMousePressed(evt);
            }
        });

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/angle-right-solid.png"))); // NOI18N
        lblNext.setText("Từ kế tiếp");
        lblNext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNextMousePressed(evt);
            }
        });

        lblVie.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVie.setForeground(new java.awt.Color(0, 204, 102));
        lblVie.setText("Vietnamese meaning");

        jLabel2.setText("Chú ý: Khi chạy thật thì chỉ 1 trong 2 label xanh hoặc đỏ xuất hiện, cái kia có thể ẩn đi hoặc setText(\"\") và xóa cái này đi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboboxChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVie)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblFlip, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNext, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEng)
                            .addComponent(lblTuHienTaiTrenSoTu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboboxChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(174, 174, 174)
                .addComponent(lblTuHienTaiTrenSoTu)
                .addGap(18, 18, 18)
                .addComponent(lblEng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVie)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrev)
                    .addComponent(lblFlip)
                    .addComponent(lblNext))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(282, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblPrevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrevMousePressed
        
    }//GEN-LAST:event_lblPrevMousePressed

    private void lblFlipMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFlipMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFlipMousePressed

    private void lblNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNextMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxChuDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEng;
    private javax.swing.JLabel lblFlip;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblPrev;
    private javax.swing.JLabel lblTuHienTaiTrenSoTu;
    private javax.swing.JLabel lblVie;
    // End of variables declaration//GEN-END:variables
}
