/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import ui.MainFrame;
import ui.frame.LoginFrame;

/**
 *
 * @author Admin
 */
public class MenuAdminPanel extends javax.swing.JPanel {

    private MainFrame mainframe ;
    private CardLayout cardlayout;

    /**
     * Creates new form MenuUserPanel
     */
    public MenuAdminPanel() {
        initComponents();
        this.mainframe = mainframe;
    }

    public MenuAdminPanel(MainFrame mainframe) {
        initComponents();
        this.mainframe = mainframe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTenAcc = new javax.swing.JLabel();
        lblQuanLyChuDe = new javax.swing.JLabel();
        lblQuanLyTu = new javax.swing.JLabel();
        lblQuanLyTaiKhoan = new javax.swing.JLabel();
        lblDSTKDaLamChuDe = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Xin chào");

        lblTenAcc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTenAcc.setForeground(new java.awt.Color(255, 255, 255));
        lblTenAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenAcc.setText("Tên admin");

        lblQuanLyChuDe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuanLyChuDe.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyChuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/list.png"))); // NOI18N
        lblQuanLyChuDe.setText("QUẢN LÝ CHỦ ĐỀ");
        lblQuanLyChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuanLyChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQuanLyChuDeMousePressed(evt);
            }
        });

        lblQuanLyTu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuanLyTu.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyTu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/char.png"))); // NOI18N
        lblQuanLyTu.setText("QUẢN LÝ TỪ");
        lblQuanLyTu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuanLyTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQuanLyTuMousePressed(evt);
            }
        });

        lblQuanLyTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuanLyTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        lblQuanLyTaiKhoan.setText("QUẢN LÝ TÀI KHOẢN");
        lblQuanLyTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuanLyTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQuanLyTaiKhoanMousePressed(evt);
            }
        });

        lblDSTKDaLamChuDe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDSTKDaLamChuDe.setForeground(new java.awt.Color(255, 255, 255));
        lblDSTKDaLamChuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/poll.png"))); // NOI18N
        lblDSTKDaLamChuDe.setText("DS TK ĐÃ LÀM CHỦ ĐỀ");
        lblDSTKDaLamChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDSTKDaLamChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDSTKDaLamChuDeMousePressed(evt);
            }
        });

        lblDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        lblDangXuat.setText("ĐĂNG XUẤT");
        lblDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDangXuatMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblQuanLyChuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQuanLyTu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQuanLyTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDSTKDaLamChuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTenAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenAcc)
                .addGap(69, 69, 69)
                .addComponent(lblQuanLyChuDe)
                .addGap(32, 32, 32)
                .addComponent(lblQuanLyTu)
                .addGap(32, 32, 32)
                .addComponent(lblQuanLyTaiKhoan)
                .addGap(32, 32, 32)
                .addComponent(lblDSTKDaLamChuDe)
                .addGap(32, 32, 32)
                .addComponent(lblDangXuat)
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblQuanLyChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyChuDeMousePressed
        
        mainframe.showPanel("QuanLyChuDe");
    }//GEN-LAST:event_lblQuanLyChuDeMousePressed

    private void lblQuanLyTuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyTuMousePressed
        if (mainframe == null) {
            System.out.println("mainframe NULL");
        }
        mainframe.showPanel("QuanLyTu");
    }//GEN-LAST:event_lblQuanLyTuMousePressed

    private void lblQuanLyTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyTaiKhoanMousePressed
        mainframe.showPanel("QuanLyTaiKhoan");
    }//GEN-LAST:event_lblQuanLyTaiKhoanMousePressed

    private void lblDSTKDaLamChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDSTKDaLamChuDeMousePressed
        // TODO add your handling code here:
        mainframe.showPanel("DanhSachTKDaLamChuDePanel");
    }//GEN-LAST:event_lblDSTKDaLamChuDeMousePressed

    private void lblDangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMousePressed
        int chon = JOptionPane.showConfirmDialog(
                this,
                "Bạn có muốn đăng xuất?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION
        );

        if (chon == JOptionPane.YES_OPTION) {

            new LoginFrame().setVisible(true);
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            frame.dispose();
        }
    }//GEN-LAST:event_lblDangXuatMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDSTKDaLamChuDe;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblQuanLyChuDe;
    private javax.swing.JLabel lblQuanLyTaiKhoan;
    private javax.swing.JLabel lblQuanLyTu;
    private javax.swing.JLabel lblTenAcc;
    // End of variables declaration//GEN-END:variables
}
