/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import ui.dialog.CRUDChuDe;
import ui.dialog.CRUDTu;

/**
 *
 * @author Admin
 */
public class QuanLyTu extends javax.swing.JPanel {

    private dao.ChuDeDAO chuDeDAO = new dao.ChuDeDAO();
    private dao.TuVungDAO tuVungDAO = new dao.TuVungDAO();

    public QuanLyTu() {
        initComponents();
        
        // Add action listener to combobox programmatically
        comboboxChuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxChuDeActionPerformed(evt);
            }
        });

        // Add mouse listener to XuatTXT programmatically
        lblXuatTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblXuatTXTMousePressed(evt);
            }
        });

        loadChuDeComboBox();
        loadData();
    }

    private void loadChuDeComboBox() {
        comboboxChuDe.removeAllItems();
        for (models.ChuDe cd : chuDeDAO.selectAll()) {
            comboboxChuDe.addItem(cd.getTenChuDe());
        }
    }

    public void loadData() {
        if (comboboxChuDe.getSelectedItem() == null) {
            return;
        }
        String tenCD = comboboxChuDe.getSelectedItem().toString();
        lblTenChuDe.setText(tenCD);
        models.ChuDe cd = chuDeDAO.selectByName(tenCD);
        if (cd != null) {
            displayWords(tuVungDAO.selectByChuDe(cd.getMaChuDe()));
        }
    }

    private void displayWords(java.util.List<models.TuVung> list) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableTu.getModel();
        model.setRowCount(0);
        int stt = 1;
        for (models.TuVung tv : list) {
            model.addRow(new Object[] {
                String.format("%02d", stt++),
                tv.getMaTu(),
                tv.getTuTiengAnh(),
                tv.getNghiaTiengViet(),
                tv.getMaChuDe()
            });
        }
        lblSoLuongTuTrongChuDe.setText(String.valueOf(list.size()));
        lblEng.setText("English word");
        lblVie.setText("Vietnamese meaning");
    }

    private void comboboxChuDeActionPerformed(java.awt.event.ActionEvent evt) {
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboboxChuDe = new javax.swing.JComboBox<>();
        lblThemTuVaoChuDe = new javax.swing.JLabel();
        lblSuaTuTrongChuDe = new javax.swing.JLabel();
        lblXoaTuTrongChuDe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTimTu = new javax.swing.JTextField();
        lblTimKiem = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSapXepTheoAlphabet = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTenChuDe = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSoLuongTuTrongChuDe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTu = new javax.swing.JTable();
        lblEng = new javax.swing.JLabel();
        lblVie = new javax.swing.JLabel();
        lblXuatTXT = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Chọn chủ đề:");

        lblThemTuVaoChuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus-solid.png"))); // NOI18N
        lblThemTuVaoChuDe.setText("Thêm từ mới vào chủ đề");
        lblThemTuVaoChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThemTuVaoChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblThemTuVaoChuDeMousePressed(evt);
            }
        });

        lblSuaTuTrongChuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pen-to-square-regular.png"))); // NOI18N
        lblSuaTuTrongChuDe.setText("Sửa 1 từ trong chủ đề");
        lblSuaTuTrongChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSuaTuTrongChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSuaTuTrongChuDeMousePressed(evt);
            }
        });

        lblXoaTuTrongChuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash-can-regular (1).png"))); // NOI18N
        lblXoaTuTrongChuDe.setText("Xóa 1 từ trong chủ đề ");
        lblXoaTuTrongChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblXoaTuTrongChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblXoaTuTrongChuDeMousePressed(evt);
            }
        });

        jLabel4.setText("Tìm kiếm từ:");

        lblTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnifying-glass-solid.png"))); // NOI18N
        lblTimKiem.setText("Tìm kiếm");
        lblTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTimKiemMousePressed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sắp xếp chủ đề theo bảng chữ cái");

        lblSapXepTheoAlphabet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow-down-a-z-solid.png"))); // NOI18N
        lblSapXepTheoAlphabet.setText("Sắp xếp");
        lblSapXepTheoAlphabet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSapXepTheoAlphabet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSapXepTheoAlphabetMousePressed(evt);
            }
        });

        jLabel2.setText("Chủ đề:");

        lblTenChuDe.setBackground(new java.awt.Color(255, 0, 0));
        lblTenChuDe.setForeground(new java.awt.Color(255, 0, 0));
        lblTenChuDe.setText("Animal");

        jLabel5.setText("Số lượng từ:");

        lblSoLuongTuTrongChuDe.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblSoLuongTuTrongChuDe.setForeground(new java.awt.Color(0, 204, 102));
        lblSoLuongTuTrongChuDe.setText("2");

        tableTu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "W1", "Elephant", "Voi", "TP1"},
                {"02", "W2", "Dolphin", "Cá heo", "TP1"},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã từ", "Tiếng Anh", "Tiếng Việt", "Mã chủ đề"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableTu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableTuMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableTu);

        lblEng.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEng.setForeground(new java.awt.Color(255, 102, 102));
        lblEng.setText("English word");

        lblVie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVie.setForeground(new java.awt.Color(0, 204, 102));
        lblVie.setText("Vietnamese meaning");

        lblXuatTXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file-export-solid (1).png"))); // NOI18N
        lblXuatTXT.setText("Xuất TXT");
        lblXuatTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEng)
                            .addComponent(lblVie)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(lblTenChuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(lblSoLuongTuTrongChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblThemTuVaoChuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSuaTuTrongChuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblXoaTuTrongChuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblXuatTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(jLabel4)
                                    .addGap(28, 28, 28)
                                    .addComponent(txtTimTu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(168, 168, 168)
                                    .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSapXepTheoAlphabet, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(comboboxChuDe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboboxChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThemTuVaoChuDe)
                    .addComponent(txtTimTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(lblSuaTuTrongChuDe)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimKiem)
                    .addComponent(lblSapXepTheoAlphabet)
                    .addComponent(lblXuatTXT))
                .addGap(18, 18, 18)
                .addComponent(lblXoaTuTrongChuDe)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTenChuDe)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuongTuTrongChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblEng)
                        .addGap(30, 30, 30)
                        .addComponent(lblVie))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblSuaTuTrongChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaTuTrongChuDeMousePressed
        int row = tableTu.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Phải chọn 1 dòng trong bảng!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String maTu = tableTu.getValueAt(row, 1).toString();
        String eng = tableTu.getValueAt(row, 2).toString();
        String vie = tableTu.getValueAt(row, 3).toString();
        String maChuDe = tableTu.getValueAt(row, 4).toString();

        CRUDTu dialog = new CRUDTu(null, true);
        CapNhatTu panel = new CapNhatTu();

        // truyền dữ liệu sang panel trước khi show
        panel.setAll(maChuDe, maTu, eng, vie);

        dialog.getContentPane().removeAll();
        dialog.getContentPane().setLayout(new BorderLayout());
        dialog.getContentPane().add(panel, BorderLayout.CENTER);

        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        loadData();
    }//GEN-LAST:event_lblSuaTuTrongChuDeMousePressed

    private void tableTuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTuMousePressed
        int row = tableTu.getSelectedRow();
        if (row == -1) {
            System.out.println("Chưa chọn dòng nào!");
            return;
        }
        lblEng.setText((String) tableTu.getValueAt(row, 2));
        lblVie.setText((String) tableTu.getValueAt(row, 3));
    }//GEN-LAST:event_tableTuMousePressed

    private void lblXoaTuTrongChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXoaTuTrongChuDeMousePressed
        int row = tableTu.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Phải chọn 1 dòng trong bảng!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int chon = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa từ này?", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        if (chon == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(tableTu.getValueAt(row, 1).toString());
            if (tuVungDAO.delete(id)) {
                JOptionPane.showMessageDialog(null, "Đã xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadData();
            } else {
                JOptionPane.showMessageDialog(null, "Xóa thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_lblXoaTuTrongChuDeMousePressed

    private void lblThemTuVaoChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemTuVaoChuDeMousePressed
        CRUDTu dialog = new CRUDTu(null, true);
        ThemTu panel = new ThemTu();
        dialog.getContentPane().removeAll();
        dialog.getContentPane().setLayout(new BorderLayout());
        dialog.getContentPane().add(panel, BorderLayout.CENTER);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        loadData();
    }//GEN-LAST:event_lblThemTuVaoChuDeMousePressed

    private void lblTimKiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTimKiemMousePressed
        if (comboboxChuDe.getSelectedItem() == null) return;
        String tenCD = comboboxChuDe.getSelectedItem().toString();
        models.ChuDe cd = chuDeDAO.selectByName(tenCD);
        if (cd == null) return;

        String keyword = txtTimTu.getText().trim().toLowerCase();
        java.util.List<models.TuVung> all = tuVungDAO.selectByChuDe(cd.getMaChuDe());
        java.util.List<models.TuVung> filtered = new java.util.ArrayList<>();
        for (models.TuVung tv : all) {
            if (tv.getTuTiengAnh().toLowerCase().contains(keyword) || tv.getNghiaTiengViet().toLowerCase().contains(keyword)) {
                filtered.add(tv);
            }
        }
        displayWords(filtered);
    }//GEN-LAST:event_lblTimKiemMousePressed

    private void lblSapXepTheoAlphabetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSapXepTheoAlphabetMousePressed
        if (comboboxChuDe.getSelectedItem() == null) return;
        String tenCD = comboboxChuDe.getSelectedItem().toString();
        models.ChuDe cd = chuDeDAO.selectByName(tenCD);
        if (cd == null) return;

        java.util.List<models.TuVung> all = tuVungDAO.selectByChuDe(cd.getMaChuDe());
        all.sort((tv1, tv2) -> tv1.getTuTiengAnh().compareToIgnoreCase(tv2.getTuTiengAnh()));
        displayWords(all);
    }//GEN-LAST:event_lblSapXepTheoAlphabetMousePressed

    private void lblXuatTXTMousePressed(java.awt.event.MouseEvent evt) {
        if (comboboxChuDe.getSelectedItem() == null) {
            return;
        }
        String tenCD = comboboxChuDe.getSelectedItem().toString();
        models.ChuDe cd = chuDeDAO.selectByName(tenCD);
        if (cd == null) return;
        
        java.util.List<models.TuVung> list = tuVungDAO.selectByChuDe(cd.getMaChuDe());
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Chủ đề này chưa có từ vựng để xuất!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        java.io.File dir = new java.io.File("report");
        if (!dir.exists()) dir.mkdirs();
        
        java.io.File file = new java.io.File(dir, "words_export_" + tenCD.toLowerCase().replace(" ", "_") + ".txt");
        try (java.io.PrintWriter writer = new java.io.PrintWriter(new java.io.OutputStreamWriter(new java.io.FileOutputStream(file), java.nio.charset.StandardCharsets.UTF_8))) {
            writer.println("DANH SÁCH TỪ VỰNG CHỦ ĐỀ: " + tenCD.toUpperCase());
            writer.println("==========================================");
            int stt = 1;
            for (models.TuVung tv : list) {
                writer.printf("%02d. %-20s : %s\n", stt++, tv.getTuTiengAnh(), tv.getNghiaTiengViet());
            }
            JOptionPane.showMessageDialog(null, "Xuất file thành công!\nĐường dẫn: " + file.getAbsolutePath(), "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Xuất file thất bại: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxChuDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEng;
    private javax.swing.JLabel lblSapXepTheoAlphabet;
    private javax.swing.JLabel lblSoLuongTuTrongChuDe;
    private javax.swing.JLabel lblSuaTuTrongChuDe;
    private javax.swing.JLabel lblTenChuDe;
    private javax.swing.JLabel lblThemTuVaoChuDe;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblVie;
    private javax.swing.JLabel lblXoaTuTrongChuDe;
    private javax.swing.JLabel lblXuatTXT;
    private javax.swing.JTable tableTu;
    private javax.swing.JTextField txtTimTu;
    // End of variables declaration//GEN-END:variables
}
