/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import ui.dialog.CRUDChuDe;
import ui.dialog.CRUDTaiKhoan;

/**
 *
 * @author Admin
 */
public class QuanLyTaiKhoan extends javax.swing.JPanel {

    private dao.TaiKhoanDAO taiKhoanDAO = new dao.TaiKhoanDAO();

    public QuanLyTaiKhoan() {
        initComponents();
        
        lblTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTimKiemMousePressed(evt);
            }
        });
        
        lblLocTheoRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLocTheoRoleMousePressed(evt);
            }
        });
        
        lblSapXepTheoAlphabet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSapXepTheoAlphabetMousePressed(evt);
            }
        });

        loadData();
    }

    public void loadData() {
        displayAccounts(taiKhoanDAO.selectAll());
    }

    private void displayAccounts(java.util.List<models.TaiKhoan> list) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableTaiKhoan.getModel();
        model.setRowCount(0);
        int stt = 1;
        for (models.TaiKhoan tk : list) {
            model.addRow(new Object[] {
                String.format("%02d", stt++),
                tk.getMaTaiKhoan(),
                tk.getTenDangNhap(),
                tk.getMatKhau(),
                tk.getVaiTro()
            });
        }
        lblSoLuongAcc.setText(String.valueOf(taiKhoanDAO.countTotal()));
        lblSoLuongAdmin.setText(String.valueOf(taiKhoanDAO.countAdmins()));
    }

    private void lblTimKiemMousePressed(java.awt.event.MouseEvent evt) {
        String keyword = txtTimTaiKhoan.getText().trim().toLowerCase();
        java.util.List<models.TaiKhoan> all = taiKhoanDAO.selectAll();
        java.util.List<models.TaiKhoan> filtered = new java.util.ArrayList<>();
        for (models.TaiKhoan tk : all) {
            if (tk.getTenDangNhap().toLowerCase().contains(keyword)) {
                filtered.add(tk);
            }
        }
        displayAccounts(filtered);
    }

    private void lblLocTheoRoleMousePressed(java.awt.event.MouseEvent evt) {
        String selectedRole = comboboxRole.getSelectedItem().toString();
        java.util.List<models.TaiKhoan> all = taiKhoanDAO.selectAll();
        java.util.List<models.TaiKhoan> filtered = new java.util.ArrayList<>();
        for (models.TaiKhoan tk : all) {
            if (tk.getVaiTro().equalsIgnoreCase(selectedRole)) {
                filtered.add(tk);
            }
        }
        displayAccounts(filtered);
    }

    private void lblSapXepTheoAlphabetMousePressed(java.awt.event.MouseEvent evt) {
        java.util.List<models.TaiKhoan> all = taiKhoanDAO.selectAll();
        all.sort((tk1, tk2) -> tk1.getTenDangNhap().compareToIgnoreCase(tk2.getTenDangNhap()));
        displayAccounts(all);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblThemTaiKhoan = new javax.swing.JLabel();
        lblSuaTaiKhoan = new javax.swing.JLabel();
        lblXoaTaiKhoan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTimTaiKhoan = new javax.swing.JTextField();
        lblTimKiem = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboboxRole = new javax.swing.JComboBox<>();
        lblLocTheoRole = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSapXepTheoAlphabet = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTaiKhoan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblSoLuongAcc = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSoLuongAdmin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblThemTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus-solid.png"))); // NOI18N
        lblThemTaiKhoan.setText("Thêm tài khoản");
        lblThemTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThemTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblThemTaiKhoanMousePressed(evt);
            }
        });

        lblSuaTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pen-to-square-regular.png"))); // NOI18N
        lblSuaTaiKhoan.setText("Sửa thông tin tài khoản");
        lblSuaTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSuaTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSuaTaiKhoanMousePressed(evt);
            }
        });

        lblXoaTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash-can-regular (1).png"))); // NOI18N
        lblXoaTaiKhoan.setText("Xóa tài khoản");
        lblXoaTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblXoaTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblXoaTaiKhoanMousePressed(evt);
            }
        });

        jLabel4.setText("Tìm kiếm username:");

        lblTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnifying-glass-solid.png"))); // NOI18N
        lblTimKiem.setText("Tìm kiếm");
        lblTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setText("Lọc theo role:");

        comboboxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));

        lblLocTheoRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/filter-solid.png"))); // NOI18N
        lblLocTheoRole.setText("Lọc");
        lblLocTheoRole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sắp xếp theo tên tài khoản");

        lblSapXepTheoAlphabet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow-down-a-z-solid.png"))); // NOI18N
        lblSapXepTheoAlphabet.setText("Sắp xếp");
        lblSapXepTheoAlphabet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tableTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "USER01", "finn", "f6844161f9f09f3662d617d4b57894543c648d2c82da63ebde4c8f0593a42f66", "User"},
                {"02", "ADMIN01", "mhieu1296", "ce7be241b6eedf067dd780122fb68b9ab1b852a6c478e1d9c5c2743632a979f5", "Admin"},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã tài khoản", "Username", "Mật khẩu (dạng hashing)", "Vai trò"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTaiKhoan);

        jLabel3.setText("Số lượng tài khoản");

        lblSoLuongAcc.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblSoLuongAcc.setForeground(new java.awt.Color(15, 118, 110));
        lblSoLuongAcc.setText("1");

        jLabel8.setText("Số lượng admin");

        lblSoLuongAdmin.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblSoLuongAdmin.setForeground(new java.awt.Color(15, 118, 110));
        lblSoLuongAdmin.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblThemTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(jLabel4))
                                    .addComponent(lblXoaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(txtTimTaiKhoan))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboboxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(lblLocTheoRole, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(lblSapXepTheoAlphabet, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSoLuongAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(lblSoLuongAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThemTaiKhoan)
                    .addComponent(jLabel4)
                    .addComponent(txtTimTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(comboboxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSuaTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXoaTaiKhoan)
                    .addComponent(lblTimKiem)
                    .addComponent(lblLocTheoRole)
                    .addComponent(lblSapXepTheoAlphabet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuongAcc)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(lblSoLuongAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblXoaTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {
        int row = tableTaiKhoan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Phải chọn 1 dòng trong bảng!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int chon = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa tài khoản này?", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        if (chon == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(tableTaiKhoan.getValueAt(row, 1).toString());
            ui.MainFrame mainFrame = (ui.MainFrame) SwingUtilities.getWindowAncestor(this);
            if (mainFrame != null && mainFrame.getCurrentUser() != null && mainFrame.getCurrentUser().getMaTaiKhoan() == id) {
                JOptionPane.showMessageDialog(null, "Bạn không thể tự xóa tài khoản của chính mình!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (taiKhoanDAO.delete(id)) {
                JOptionPane.showMessageDialog(null, "Đã xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadData();
            } else {
                JOptionPane.showMessageDialog(null, "Xóa thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void lblThemTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {
        CRUDTaiKhoan dialog = new CRUDTaiKhoan(null, true);
        ThemTaiKhoan panel = new ThemTaiKhoan();
        dialog.getContentPane().removeAll();
        dialog.getContentPane().setLayout(new BorderLayout());
        dialog.getContentPane().add(panel, BorderLayout.CENTER);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        loadData();
    }

    private void lblSuaTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {
        int row = tableTaiKhoan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Phải chọn 1 dòng trong bảng!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String maTaiKhoan = tableTaiKhoan.getValueAt(row, 1).toString();
        String username = tableTaiKhoan.getValueAt(row, 2).toString();
        String vaiTro = tableTaiKhoan.getValueAt(row, 4).toString();

        CRUDTaiKhoan dialog = new CRUDTaiKhoan(null, true);
        CapNhatTaiKhoan panel = new CapNhatTaiKhoan();
        panel.setAll(maTaiKhoan, username, vaiTro);

        dialog.getContentPane().removeAll();
        dialog.getContentPane().setLayout(new BorderLayout());
        dialog.getContentPane().add(panel, BorderLayout.CENTER);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        loadData();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxRole;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLocTheoRole;
    private javax.swing.JLabel lblSapXepTheoAlphabet;
    private javax.swing.JLabel lblSoLuongAcc;
    private javax.swing.JLabel lblSoLuongAdmin;
    private javax.swing.JLabel lblSuaTaiKhoan;
    private javax.swing.JLabel lblThemTaiKhoan;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblXoaTaiKhoan;
    private javax.swing.JTable tableTaiKhoan;
    private javax.swing.JTextField txtTimTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
