/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import ui.dialog.CRUDChuDe;

/**
 *
 * @author Admin
 */
public class QuanLyChuDe extends javax.swing.JPanel {

    private CRUDChuDe crudchude;
    private ThemChuDe themchude;
    private JTextField txtChuDe;
    private final services.ChuDeService chuDeService = new services.ChuDeService();

    /**
     * Creates new form QuanLyChuDe
     */
    public QuanLyChuDe() {
        initComponents();
        tintIcons();
        loadData();
    }

    private void tintIcons() {
        java.awt.Color tealColor = new java.awt.Color(15, 118, 110);
        lblThemChuDe.setIcon(utils.ImageUtils.tintIcon(lblThemChuDe.getIcon(), tealColor));
        lblSuaChuDe.setIcon(utils.ImageUtils.tintIcon(lblSuaChuDe.getIcon(), tealColor));
        lblXoaChuDe.setIcon(utils.ImageUtils.tintIcon(lblXoaChuDe.getIcon(), tealColor));
        lblTimKiem.setIcon(utils.ImageUtils.tintIcon(lblTimKiem.getIcon(), tealColor));
        lblSapXepTheoAlphabet.setIcon(utils.ImageUtils.tintIcon(lblSapXepTheoAlphabet.getIcon(), tealColor));
    }

    public void loadData() {
        displayTopics(chuDeService.getAllTopics());
    }

    private void displayTopics(java.util.List<models.ChuDe> list) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableChuDe.getModel();
        model.setRowCount(0);
        int stt = 1;
        for (models.ChuDe cd : list) {
            model.addRow(new Object[] {
                String.format("%02d", stt++),
                cd.getMaChuDe(),
                cd.getTenChuDe()
            });
        }
        lblSoLuongChuDe.setText(String.valueOf(chuDeService.countTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblThemChuDe = new javax.swing.JLabel();
        lblSuaChuDe = new javax.swing.JLabel();
        lblXoaChuDe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTimChuDe = new javax.swing.JTextField();
        lblTimKiem = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSapXepTheoAlphabet = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChuDe = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblSoLuongChuDe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblThemChuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus-solid.png"))); // NOI18N
        lblThemChuDe.setText("Thêm chủ đề mới");
        lblThemChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThemChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblThemChuDeMousePressed(evt);
            }
        });

        lblSuaChuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pen-to-square-regular.png"))); // NOI18N
        lblSuaChuDe.setText("Sửa chủ đề ");
        lblSuaChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSuaChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSuaChuDeMousePressed(evt);
            }
        });

        lblXoaChuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash-can-regular (1).png"))); // NOI18N
        lblXoaChuDe.setText("Xóa chủ đề ");
        lblXoaChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblXoaChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblXoaChuDeMousePressed(evt);
            }
        });

        jLabel4.setText("Tìm kiếm chủ đề:");

        lblTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnifying-glass-solid.png"))); // NOI18N
        lblTimKiem.setText("Tìm kiếm");
        lblTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTimKiemMousePressed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sắp xếp chủ đề theo bảng chữ cái");

        lblSapXepTheoAlphabet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow-down-a-z-solid.png"))); // NOI18N
        lblSapXepTheoAlphabet.setText("Sắp xếp");
        lblSapXepTheoAlphabet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSapXepTheoAlphabet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSapXepTheoAlphabetMousePressed(evt);
            }
        });

        tableChuDe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "TP1", "Animal"},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã chủ đề", "Tên chủ đề"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableChuDe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableChuDe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableChuDe);

        jLabel1.setText("Số lượng chủ đề:");

        lblSoLuongChuDe.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblSoLuongChuDe.setForeground(new java.awt.Color(15, 118, 110));
        lblSoLuongChuDe.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuaChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblThemChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(142, 142, 142)
                                        .addComponent(jLabel4))
                                    .addComponent(lblXoaChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTimChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSapXepTheoAlphabet, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblSoLuongChuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(766, 766, 766)))
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThemChuDe)
                    .addComponent(jLabel4)
                    .addComponent(txtTimChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(lblSuaChuDe)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXoaChuDe)
                    .addComponent(lblTimKiem)
                    .addComponent(lblSapXepTheoAlphabet))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSoLuongChuDe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblThemChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemChuDeMousePressed
        CRUDChuDe dialog = new CRUDChuDe(null, true);
        ThemChuDe panel = new ThemChuDe();
        dialog.getContentPane().removeAll();
        dialog.getContentPane().setLayout(new BorderLayout());
        dialog.getContentPane().add(panel, BorderLayout.CENTER);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        loadData();
    }//GEN-LAST:event_lblThemChuDeMousePressed

    private void lblSuaChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaChuDeMousePressed
        int row = tableChuDe.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Phải chọn 1 dòng trong bảng!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String maCD = tableChuDe.getValueAt(row, 1).toString();
        String tenCD = tableChuDe.getValueAt(row, 2).toString();

        CRUDChuDe dialog = new CRUDChuDe(null, true);
        CapNhatChuDe panel = new CapNhatChuDe();

        // truyền dữ liệu sang panel trước khi show
        panel.setTenChuDe(tenCD);
        panel.setMaChuDe(maCD);
        
        dialog.getContentPane().removeAll();
        dialog.getContentPane().setLayout(new BorderLayout());
        dialog.getContentPane().add(panel, BorderLayout.CENTER);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        loadData();
    }//GEN-LAST:event_lblSuaChuDeMousePressed

    private void lblXoaChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXoaChuDeMousePressed
        int row = tableChuDe.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Phải chọn 1 dòng trong bảng!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int chon = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa chủ đề này? Hành động này sẽ xóa mọi từ vựng liên quan.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        if (chon == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(tableChuDe.getValueAt(row, 1).toString());
            if (chuDeService.deleteTopic(id)) {
                JOptionPane.showMessageDialog(null, "Đã xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadData();
            } else {
                JOptionPane.showMessageDialog(null, "Xóa thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_lblXoaChuDeMousePressed

    private void lblTimKiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTimKiemMousePressed
        String keyword = txtTimChuDe.getText().trim().toLowerCase();
        java.util.List<models.ChuDe> all = chuDeService.getAllTopics();
        java.util.List<models.ChuDe> filtered = new java.util.ArrayList<>();
        for (models.ChuDe cd : all) {
            if (cd.getTenChuDe().toLowerCase().contains(keyword)) {
                filtered.add(cd);
            }
        }
        displayTopics(filtered);
    }//GEN-LAST:event_lblTimKiemMousePressed

    private void lblSapXepTheoAlphabetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSapXepTheoAlphabetMousePressed
        java.util.List<models.ChuDe> all = chuDeService.getAllTopics();
        all.sort((cd1, cd2) -> cd1.getTenChuDe().compareToIgnoreCase(cd2.getTenChuDe()));
        displayTopics(all);
    }//GEN-LAST:event_lblSapXepTheoAlphabetMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSapXepTheoAlphabet;
    private javax.swing.JLabel lblSoLuongChuDe;
    private javax.swing.JLabel lblSuaChuDe;
    private javax.swing.JLabel lblThemChuDe;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblXoaChuDe;
    private javax.swing.JTable tableChuDe;
    private javax.swing.JTextField txtTimChuDe;
    // End of variables declaration//GEN-END:variables
}
