/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import ui.dialog.CRUDChuDe;

/**
 *
 * @author Admin
 */
public class QuanLyChuDe extends javax.swing.JPanel {

    private CRUDChuDe crudchude;
    private ThemChuDe themchude;
    private JTextField txtChuDe;

    /**
     * Creates new form QuanLyChuDe
     */
    public QuanLyChuDe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblThemChuDe = new javax.swing.JLabel();
        lblSuaChuDe = new javax.swing.JLabel();
        lblXoaChuDe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTimChuDe = new javax.swing.JTextField();
        lblTimKiem = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSapXepTheoAlphabet = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChuDe = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblThemChuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus-solid.png"))); // NOI18N
        lblThemChuDe.setText("Thêm chủ đề mới");
        lblThemChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThemChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblThemChuDeMousePressed(evt);
            }
        });

        lblSuaChuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pen-to-square-regular.png"))); // NOI18N
        lblSuaChuDe.setText("Sửa chủ đề ");
        lblSuaChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSuaChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSuaChuDeMousePressed(evt);
            }
        });

        lblXoaChuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash-can-regular (1).png"))); // NOI18N
        lblXoaChuDe.setText("Xóa chủ đề ");
        lblXoaChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblXoaChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblXoaChuDeMousePressed(evt);
            }
        });

        jLabel4.setText("Tìm kiếm chủ đề:");

        lblTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnifying-glass-solid.png"))); // NOI18N
        lblTimKiem.setText("Tìm kiếm");
        lblTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTimKiemMousePressed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sắp xếp chủ đề theo bảng chữ cái");

        lblSapXepTheoAlphabet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow-down-a-z-solid.png"))); // NOI18N
        lblSapXepTheoAlphabet.setText("Sắp xếp");
        lblSapXepTheoAlphabet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSapXepTheoAlphabet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSapXepTheoAlphabetMousePressed(evt);
            }
        });

        tableChuDe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "TP1", "Animal"},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã chủ đề", "Tên chủ đề"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableChuDe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableChuDe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableChuDe);

        jLabel1.setText("Số lượng chủ đề:");

        jLabel2.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 102));
        jLabel2.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuaChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblThemChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(142, 142, 142)
                                        .addComponent(jLabel4))
                                    .addComponent(lblXoaChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTimChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSapXepTheoAlphabet, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(766, 766, 766)))
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThemChuDe)
                    .addComponent(jLabel4)
                    .addComponent(txtTimChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(lblSuaChuDe)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXoaChuDe)
                    .addComponent(lblTimKiem)
                    .addComponent(lblSapXepTheoAlphabet))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblThemChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemChuDeMousePressed
        CRUDChuDe dialog = new CRUDChuDe(null, true);

        ThemChuDe panel = new ThemChuDe();

        dialog.getContentPane().removeAll();
        dialog.getContentPane().setLayout(new BorderLayout());
        dialog.getContentPane().add(panel, BorderLayout.CENTER);

        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_lblThemChuDeMousePressed

    private void lblSuaChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaChuDeMousePressed
//        int row = tableChuDe.getSelectedRow();
//        System.out.println(row);
//        
//        CRUDChuDe dialog = new CRUDChuDe(null, true);
//
//        CapNhatChuDe panel = new CapNhatChuDe();
//
//        dialog.getContentPane().removeAll();
//        dialog.getContentPane().setLayout(new BorderLayout());
//        dialog.getContentPane().add(panel, BorderLayout.CENTER);
//        
//        dialog.pack();
//        dialog.setLocationRelativeTo(null);
//        dialog.setVisible(true);
//        
//        String tenCD = tableChuDe.getValueAt(row, 1).toString();
//        System.out.println(tenCD);
//        txtChuDe.setText(tenCD);
        int row = tableChuDe.getSelectedRow();

        if (row == -1) {
            System.out.println("Chưa chọn dòng nào!");
            return;
        }
        
        String maCD = tableChuDe.getValueAt(row, 1).toString();
        String tenCD = tableChuDe.getValueAt(row, 2).toString();
        System.out.println("tenCD = " + tenCD);

        CRUDChuDe dialog = new CRUDChuDe(null, true);
        CapNhatChuDe panel = new CapNhatChuDe();

        // truyền dữ liệu sang panel trước khi show
        panel.setTenChuDe(tenCD);   // bạn cần tạo hàm này
        panel.setMaChuDe(maCD);
        
        dialog.getContentPane().removeAll();
        dialog.getContentPane().setLayout(new BorderLayout());
        dialog.getContentPane().add(panel, BorderLayout.CENTER);

        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_lblSuaChuDeMousePressed

    private void lblXoaChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXoaChuDeMousePressed
        int chon = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa chủ đề này?", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        if (chon == JOptionPane.YES_OPTION) {
            // gọi phương thức xóa từ trong service
            
            JOptionPane.showMessageDialog(null, "Đã xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
//        JOptionPane.showConfirmDialog(crudchude, evt, TOOL_TIP_TEXT_KEY, WIDTH)
    }//GEN-LAST:event_lblXoaChuDeMousePressed

    private void lblTimKiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTimKiemMousePressed
        // TODO add your handling code here:
        // gọi hàm từ service, services gọi dao và dao gọi db để lấy data
    }//GEN-LAST:event_lblTimKiemMousePressed

    private void lblSapXepTheoAlphabetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSapXepTheoAlphabetMousePressed
        // TODO add your handling code here:
                // gọi hàm từ service, services gọi dao và dao gọi db để lấy data

    }//GEN-LAST:event_lblSapXepTheoAlphabetMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSapXepTheoAlphabet;
    private javax.swing.JLabel lblSuaChuDe;
    private javax.swing.JLabel lblThemChuDe;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblXoaChuDe;
    private javax.swing.JTable tableChuDe;
    private javax.swing.JTextField txtTimChuDe;
    // End of variables declaration//GEN-END:variables
}
