/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panel;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Admin
 */
public class ThemChuDe extends javax.swing.JPanel {

    /**
     * Creates new form ThemChuDe
     */
    public ThemChuDe() {
        initComponents();
        txtMaChuDe.setEnabled(false);
        txtMaChuDe.setText("(Tự động sinh)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtChuDe = new javax.swing.JTextField();
        lblThemChuDe = new javax.swing.JLabel();
        lblHuyThemChuDe = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaChuDe = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(248, 250, 252));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM CHỦ ĐỀ MỚI");
        jLabel1.setOpaque(true);

        jLabel2.setText("Tên chủ đề");

        lblThemChuDe.setBackground(new java.awt.Color(15, 118, 110));
        lblThemChuDe.setForeground(new java.awt.Color(255, 255, 255));
        lblThemChuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThemChuDe.setText("Thêm");
        lblThemChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThemChuDe.setOpaque(true);
        lblThemChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblThemChuDeMousePressed(evt);
            }
        });

        lblHuyThemChuDe.setBackground(new java.awt.Color(255, 0, 0));
        lblHuyThemChuDe.setForeground(new java.awt.Color(255, 255, 255));
        lblHuyThemChuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuyThemChuDe.setText("Hủy");
        lblHuyThemChuDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHuyThemChuDe.setOpaque(true);
        lblHuyThemChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHuyThemChuDeMousePressed(evt);
            }
        });

        jLabel3.setText("Mã chủ đề");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblThemChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblHuyThemChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMaChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThemChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHuyThemChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblHuyThemChuDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuyThemChuDeMousePressed
        // TODO add your handling code here:
        JDialog frame = (JDialog) SwingUtilities.getWindowAncestor(this);
            frame.dispose();

    }//GEN-LAST:event_lblHuyThemChuDeMousePressed

    private void lblThemChuDeMousePressed(java.awt.event.MouseEvent evt) {
        String chude = txtChuDe.getText().trim();
        if (chude.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Chủ đề không được để trống!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        dao.ChuDeDAO chuDeDAO = new dao.ChuDeDAO();
        if (chuDeDAO.selectByName(chude) != null) {
            JOptionPane.showMessageDialog(null, "Tên chủ đề đã tồn tại!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        models.ChuDe cd = new models.ChuDe(0, chude);
        if (chuDeDAO.insert(cd)) {
            JOptionPane.showMessageDialog(null, "Thêm chủ đề thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            JDialog frame = (JDialog) SwingUtilities.getWindowAncestor(this);
            frame.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Thêm chủ đề thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblHuyThemChuDe;
    private javax.swing.JLabel lblThemChuDe;
    private javax.swing.JTextField txtChuDe;
    private javax.swing.JTextField txtMaChuDe;
    // End of variables declaration//GEN-END:variables
}
