package ui.panel;

import javax.swing.table.DefaultTableModel;
import javax.swing.SwingUtilities;
import java.util.List;
import java.util.ArrayList;
import ui.MainFrame;

public class TongQuan extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private dao.ChuDeDAO chuDeDAO = new dao.ChuDeDAO();
    private dao.KetQuaKiemTraDAO ketQuaKiemTraDAO = new dao.KetQuaKiemTraDAO();

    /**
     * Creates new form TongQuan
     */
    public TongQuan() {
        initComponents();
    }

    public TongQuan(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();

        // Add action listener to combobox programmatically
        comboboxChuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxChuDeActionPerformed(evt);
            }
        });

        loadChuDeComboBox();
        loadData();
    }

    private models.TaiKhoan getCurrentUser() {
        if (mainFrame != null) {
            return mainFrame.getCurrentUser();
        }
        java.awt.Container parent = SwingUtilities.getWindowAncestor(this);
        if (parent instanceof MainFrame) {
            return ((MainFrame) parent).getCurrentUser();
        }
        return null;
    }

    public void loadChuDeComboBox() {
        comboboxChuDe.removeAllItems();
        comboboxChuDe.addItem("Tất cả");
        for (models.ChuDe cd : chuDeDAO.selectAll()) {
            comboboxChuDe.addItem(cd.getTenChuDe());
        }
    }

    public void loadData() {
        models.TaiKhoan user = getCurrentUser();
        if (user == null) {
            return;
        }

        // Load stats
        int totalChuDe = chuDeDAO.selectAll().size();
        int completedChuDe = ketQuaKiemTraDAO.countChuDeDaLam(user.getMaTaiKhoan());
        double avgScore = ketQuaKiemTraDAO.getDiemTrungBinh(user.getMaTaiKhoan());

        lblTongSoChuDe.setText(String.valueOf(totalChuDe));
        lblSoChuDeDaLamBaiKiemTra.setText(String.valueOf(completedChuDe));
        lblDiemTrungBinh.setText(String.format("%.2f", avgScore));

        // Load table results
        loadTableResults();
    }

    private void loadTableResults() {
        models.TaiKhoan user = getCurrentUser();
        if (user == null || comboboxChuDe.getSelectedItem() == null) {
            return;
        }

        String selectedTopic = comboboxChuDe.getSelectedItem().toString();
        List<models.KetQuaKiemTra> list;
        if ("Tất cả".equals(selectedTopic)) {
            list = ketQuaKiemTraDAO.selectByTaiKhoan(user.getMaTaiKhoan());
        } else {
            models.ChuDe cd = chuDeDAO.selectByName(selectedTopic);
            list = new ArrayList<>();
            if (cd != null) {
                List<models.KetQuaKiemTra> all = ketQuaKiemTraDAO.selectByTaiKhoan(user.getMaTaiKhoan());
                for (models.KetQuaKiemTra kq : all) {
                    if (kq.getMaChuDe() == cd.getMaChuDe()) {
                        list.add(kq);
                    }
                }
            }
        }

        DefaultTableModel model = new DefaultTableModel(
            new Object[][] {},
            new String[] {"STT", "Chủ đề", "Điểm số", "Tổng số câu", "Thời điểm"}
        ) {
            boolean[] canEdit = new boolean[] {false, false, false, false, false};
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        int stt = 1;
        for (models.KetQuaKiemTra kq : list) {
            models.ChuDe cd = chuDeDAO.selectById(kq.getMaChuDe());
            String tenCD = (cd != null) ? cd.getTenChuDe() : "Chủ đề #" + kq.getMaChuDe();
            model.addRow(new Object[] {
                String.format("%02d", stt++),
                tenCD,
                kq.getDiemSo(),
                kq.getTongSoCau(),
                kq.getThoiDiemLamBai()
            });
        }
        tableKetQua.setModel(model);
    }

    private void comboboxChuDeActionPerformed(java.awt.event.ActionEvent evt) {
        loadTableResults();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTongSoChuDe = new javax.swing.JLabel();
        lblSoChuDeDaLamBaiKiemTra = new javax.swing.JLabel();
        lblDiemTrungBinh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKetQua = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        comboboxChuDe = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TỔNG QUAN");

        jLabel2.setText("Tổng số chủ đề");

        jLabel3.setText("Số chủ đề đã làm bài kiểm tra");

        jLabel4.setText("Điểm trung bình");

        lblTongSoChuDe.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblTongSoChuDe.setForeground(new java.awt.Color(0, 204, 102));
        lblTongSoChuDe.setText("1");

        lblSoChuDeDaLamBaiKiemTra.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblSoChuDeDaLamBaiKiemTra.setForeground(new java.awt.Color(0, 204, 102));
        lblSoChuDeDaLamBaiKiemTra.setText("1");

        lblDiemTrungBinh.setFont(new java.awt.Font("UTM HelvetIns", 0, 36)); // NOI18N
        lblDiemTrungBinh.setForeground(new java.awt.Color(0, 204, 102));
        lblDiemTrungBinh.setText("8.25");

        tableKetQua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã kết quả", "Mã chủ đề", "Điểm số", "Thời điểm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableKetQua);

        jLabel8.setText("Chọn chủ đề: ");

        comboboxChuDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblTongSoChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblSoChuDeDaLamBaiKiemTra, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblDiemTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(comboboxChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboboxChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblTongSoChuDe)
                    .addComponent(lblSoChuDeDaLamBaiKiemTra)
                    .addComponent(lblDiemTrungBinh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxChuDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiemTrungBinh;
    private javax.swing.JLabel lblSoChuDeDaLamBaiKiemTra;
    private javax.swing.JLabel lblTongSoChuDe;
    private javax.swing.JTable tableKetQua;
    // End of variables declaration//GEN-END:variables
}
