/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
// thiết kế giao diện chính ở đây 
// dạng menu bên trái, content bên phải

import java.awt.CardLayout;
import javax.swing.AbstractButton;
import ui.panel.DanhSachTKDaLamChuDePanel;
import ui.panel.MenuAdminPanel;
import ui.panel.MenuUserPanel;
import ui.panel.QuanLyChuDe;
import ui.panel.QuanLyTaiKhoan;
import ui.panel.QuanLyTu;

// đây là panel chính, chỉ chia layout
// còn những thứ đổ lên layout sẽ được thiết kế sau
/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    private CardLayout cardLayout;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form Temp
     */
    public MainFrame() {
        initComponents();
        khoiTaoCardLayout();
    }

    public void showPanel(String panelName) {
        cardLayout.show(informationPanel, panelName);
    }

    private void khoiTaoCardLayout() {

        MenuAdminPanel menu = new MenuAdminPanel(this);
        if (1 == 1) { // viết điều kiện kiểm tra người dùng có vai trò không phải admin
            cardLayout = (CardLayout) informationPanel.getLayout();

            menuPanel.add(menu);

            informationPanel.add(new QuanLyChuDe(), "QuanLyChuDe");
            informationPanel.add(new QuanLyTu(), "QuanLyTu");
            informationPanel.add(new QuanLyTaiKhoan(), "QuanLyTaiKhoan");
            informationPanel.add(new DanhSachTKDaLamChuDePanel(), "DanhSachTKDaLamChuDePanel");
            cardLayout.show(informationPanel, "QuanLyChuDe");
        } else { // admin
            System.out.println("");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        informationPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(255, 204, 204));
        menuPanel.setPreferredSize(new java.awt.Dimension(260, 720));
        menuPanel.setLayout(new java.awt.CardLayout());

        informationPanel.setBackground(new java.awt.Color(255, 255, 255));
        informationPanel.setPreferredSize(new java.awt.Dimension(1014, 720));
        informationPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(informationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel informationPanel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
